///Step 1///
run "SmokeTestsEdge/Open/OpenWord"
run "SmokeTestsEdge/SmokeTests/Word/MS Word 2016 - 03. Funktionen - XPS Dokument Erstellen und Öffnen - Citrix/Create_Word_With_Xps"
wait 2
run "SmokeTestsEdge/SmokeTests/Word/MS Word 2016 - 03. Funktionen - XPS Dokument Erstellen und Öffnen - Citrix/Steps/Step1"
wait 2
run "SmokeTestsEdge/Open/OpenWord"
run "SmokeTestsEdge/SmokeTests/Word/MS Word 2016 - 03. Funktionen - XPS Dokument Erstellen und Öffnen - Citrix/Delete_Word_With_Xps"
LogSuccess "Step1 erfolgreich durchgeführt"
LogSuccess "XPS Datei wurde mit PDF-XChange geöffnet"


